language: python
sudo: false
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - PYTHONPATH=$TRAVIS_BUILD_DIR/debug:$PYTHONPATH
script:
  nosetests --verbose --with-coverage --cover-package=macros tests
after_success:
  coveralls
